/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: ../sanity.schema.json
export type MediaItem = {
  _type: 'mediaItem'
  src: string
  alt: string
  gif?: string
  mp4?: string
  position: number
}

export type LocalizedParagraphArray = Array<{
  en: string
  es: string
  _type: 'paragraphBlock'
  _key: string
}>

export type LocalizedText = {
  _type: 'localizedText'
  en: string
  es: string
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type PostReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'post'
}

export type ProjectReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'project'
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'page' | 'post' | 'project'
  href?: string
  page?: PageReference
  post?: PostReference
  project?: ProjectReference
  openInNewTab?: boolean
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type CallToAction = {
  _type: 'callToAction'
  eyebrow?: string
  heading: string
  body?: BlockContentTextOnly
  button?: Button
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  theme?: 'light' | 'dark'
  contentAlignment?: 'textFirst' | 'imageFirst'
}

export type InfoSection = {
  _type: 'infoSection'
  heading?: string
  subheading?: string
  content?: BlockContent
}

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'page' | 'post'
        href?: string
        page?: PageReference
        post?: PostReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type LocaleString = {
  _type: 'localeString'
  es?: string
  en?: string
}

export type Button = {
  _type: 'button'
  buttonText?: string
  link?: Link
}

export type SiteVisit = {
  _type: 'siteVisit'
  photoUrl?: string
  project?: ProjectReference
  gridSpan?: '1' | '2' | 'large'
  caption?: LocaleString
}

export type ConstructionGallery = {
  _id: string
  _type: 'constructionGallery'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  visits?: Array<
    {
      _key: string
    } & SiteVisit
  >
}

export type Colaborator = {
  _id: string
  _type: 'colaborator'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  role: {
    es: string
    en: string
  }
  description?: {
    es?: string
    en?: string
  }
  quote?: {
    es?: string
    en?: string
  }
  photoUrl?: string
  order?: number
}

export type Customer = {
  _id: string
  _type: 'customer'
  _createdAt: string
  _updatedAt: string
  _rev: string
  company: string
  contact?: string
  logo?: string
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: LocaleString
  description?: {
    es?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal'
      listItem?: never
      markDefs?: Array<{
        linkType?: 'href' | 'page' | 'post' | 'project'
        href?: string
        page?: PageReference
        post?: PostReference
        project?: ProjectReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    en?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal'
      listItem?: never
      markDefs?: Array<{
        linkType?: 'href' | 'page' | 'post' | 'project'
        href?: string
        page?: PageReference
        post?: PostReference
        project?: ProjectReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
  }
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  order: number
  title: LocalizedText
  slug: Slug
  story?: LocalizedParagraphArray
  category: LocalizedText
  location?: LocalizedText
  area?: string
  year?: string
  gridColumns: '1' | '2' | '3'
  grid_variant: number
  ogImage?: string
  portfolio_image: string
  other_projects_image: string
  project_page_image: string
  information_media?: Array<
    {
      _key: string
    } & MediaItem
  >
  gallery_media: Array<
    {
      _key: string
    } & MediaItem
  >
  model3d_url?: string
  status: 'draft' | 'published' | 'archived'
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: LocaleString
  description?: LocaleString
  slug?: Slug
  heading: string
  subheading?: string
  pageBuilder?: Array<
    | ({
        _key: string
      } & CallToAction)
    | ({
        _key: string
      } & InfoSection)
  >
}

export type PersonReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'person'
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  content?: BlockContent
  excerpt?: string
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  date?: string
  author?: PersonReference
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName: string
  lastName: string
  picture: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | MediaItem
  | LocalizedParagraphArray
  | LocalizedText
  | PageReference
  | PostReference
  | ProjectReference
  | Link
  | SanityImageAssetReference
  | CallToAction
  | InfoSection
  | BlockContentTextOnly
  | BlockContent
  | LocaleString
  | Button
  | SiteVisit
  | ConstructionGallery
  | Colaborator
  | Customer
  | Settings
  | SanityImageCrop
  | SanityImageHotspot
  | Project
  | Slug
  | Page
  | PersonReference
  | Post
  | Person
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]
export type SettingsQueryResult = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: LocaleString
  description?: {
    es?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal'
      listItem?: never
      markDefs?: Array<{
        linkType?: 'href' | 'page' | 'post' | 'project'
        href?: string
        page?: PageReference
        post?: PostReference
        project?: ProjectReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    en?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal'
      listItem?: never
      markDefs?: Array<{
        linkType?: 'href' | 'page' | 'post' | 'project'
        href?: string
        page?: PageReference
        post?: PostReference
        project?: ProjectReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
  }
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
} | null

// Source: sanity/lib/queries.ts
// Variable: allCollaboratorsQuery
// Query: *[_type == "colaborator"] | order(order asc) {  _id,  name,  "role": select($locale == "es" => role.es, role.en),  "description": select($locale == "es" => description.es, description.en),  "quote": select($locale == "es" => quote.es, quote.en),  photoUrl}
export type AllCollaboratorsQueryResult = Array<{
  _id: string
  name: string
  role: string
  description: string | null
  quote: string | null
  photoUrl: string | null
}>

// Source: sanity/lib/queries.ts
// Variable: metadataProjectQuery
// Query: {    "project": *[_type == "project" && slug.current == $slug][0] {      "title": select($locale == "es" => title.es, title.en),      "story": story[]{        "en": en,        "es": es      },      "ogImage": ogImage,      "portfolio_image": portfolio_image    },    "settings": *[_type == "settings"][0] {      "siteTitle": select($locale == "es" => title.es, title.en),      ogImage    }  }
export type MetadataProjectQueryResult = {
  project: {
    title: string
    story: Array<{
      en: string
      es: string
    }> | null
    ogImage: string | null
    portfolio_image: string
  } | null
  settings: {
    siteTitle: string | null
    ogImage: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      metadataBase?: string
      _type: 'image'
    } | null
  } | null
}

// Source: sanity/lib/queries.ts
// Variable: metadataPageQuery
// Query: {    "page": *[_type == "page" && slug.current == $slug][0] {      "title": select($locale == "es" => title.es, title.en),      "description": select($locale == "es" => description.es, description.en),      "ogImage": ogImage    },    "settings": *[_type == "settings"][0] {      "siteTitle": select($locale == "es" => title.es, title.en),      ogImage    }  }
export type MetadataPageQueryResult = {
  page: {
    title: string | null
    description: string | null
    ogImage: null
  } | null
  settings: {
    siteTitle: string | null
    ogImage: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      metadataBase?: string
      _type: 'image'
    } | null
  } | null
}

// Source: sanity/lib/queries.ts
// Variable: getPageQuery
// Query: *[_type == 'page' && slug.current == $slug][0]{    _id,    _type,    name,    slug,    heading,    subheading,    "pageBuilder": pageBuilder[]{      ...,      _type == "callToAction" => {        ...,        button {          ...,            link {      ...,        _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }      }        }      },      _type == "infoSection" => {        content[]{          ...,          markDefs[]{            ...,              _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }          }        }      },    },  }
export type GetPageQueryResult = {
  _id: string
  _type: 'page'
  name: null
  slug: Slug | null
  heading: string
  subheading: string | null
  pageBuilder: Array<
    | {
        _key: string
        _type: 'callToAction'
        eyebrow?: string
        heading: string
        body?: BlockContentTextOnly
        button: {
          _type: 'button'
          buttonText?: string
          link: {
            _type: 'link'
            linkType?: 'href' | 'page' | 'post' | 'project'
            href?: string
            page: string | null
            post: string | null
            project?: ProjectReference
            openInNewTab?: boolean
          } | null
        } | null
        image?: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        theme?: 'dark' | 'light'
        contentAlignment?: 'imageFirst' | 'textFirst'
      }
    | {
        _key: string
        _type: 'infoSection'
        heading?: string
        subheading?: string
        content: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
              listItem?: 'bullet' | 'number'
              markDefs: Array<{
                linkType?: 'href' | 'page' | 'post'
                href?: string
                page: string | null
                post: string | null
                openInNewTab?: boolean
                _type: 'link'
                _key: string
              }> | null
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
              markDefs: null
            }
        > | null
      }
  > | null
} | null

// Source: sanity/lib/queries.ts
// Variable: sitemapData
// Query: *[_type == "page" || _type == "project" && defined(slug.current)] | order(_type asc) {    "slug": slug.current,    _type,    _updatedAt,  }
export type SitemapDataResult = Array<
  | {
      slug: string | null
      _type: 'page'
      _updatedAt: string
    }
  | {
      slug: string
      _type: 'project'
      _updatedAt: string
    }
>

// Source: sanity/lib/queries.ts
// Variable: allPostsQuery
// Query: *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type AllPostsQueryResult = Array<{
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: string | null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string
  author: {
    firstName: string
    lastName: string
    picture: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  } | null
}>

// Source: sanity/lib/queries.ts
// Variable: morePostsQuery
// Query: *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type MorePostsQueryResult = Array<{
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: string | null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string
  author: {
    firstName: string
    lastName: string
    picture: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  } | null
}>

// Source: sanity/lib/queries.ts
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug] [0] {    content[]{    ...,    markDefs[]{      ...,        _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }    }  },      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type PostQueryResult = {
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs: Array<{
          linkType?: 'href' | 'page' | 'post'
          href?: string
          page: string | null
          post: string | null
          openInNewTab?: boolean
          _type: 'link'
          _key: string
        }> | null
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
        markDefs: null
      }
  > | null
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: string | null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string
  author: {
    firstName: string
    lastName: string
    picture: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  } | null
} | null

// Source: sanity/lib/queries.ts
// Variable: postPagesSlugs
// Query: *[_type == "post" && defined(slug.current)]  {"slug": slug.current}
export type PostPagesSlugsResult = Array<{
  slug: string
}>

// Source: sanity/lib/queries.ts
// Variable: pagesSlugs
// Query: *[_type == "page" && defined(slug.current)]  {"slug": slug.current}
export type PagesSlugsResult = Array<{
  slug: string
}>

// Source: sanity/lib/queries.ts
// Variable: allCustomers
// Query: *[_type == "customer"] {     company, contact, logo    }
export type AllCustomersResult = Array<{
  company: string
  contact: string | null
  logo: string | null
}>

// Source: sanity/lib/queries.ts
// Variable: allProjectsQuery
// Query: * [_type == "project" && defined(slug.current)] | order(order asc) {      _id,  _type,  _updatedAt,  "status": select(_id in path("drafts.**") => "draft", "published"),  "title": select($locale == "es" => title.es, title.en),  "slug": slug.current,  "category": select($locale == "es" => category.es, category.en),  "area": area,  "year": year,  "location": select($locale == "es" => location.es, location.en),  "story": story[]{    "en": en,    "es": es  },  "portfolio_image": portfolio_image,  "other_projects_image": other_projects_image,  "project_page_image": project_page_image,  gallery_media[]{    src,    alt,    gif,    mp4,    position  },  information_media[]{    src,    alt,    gif,    mp4,    position  },  gridColumns,  grid_variant,  model3d_url,  "date": coalesce(date, _updatedAt)}
export type AllProjectsQueryResult = Array<{
  _id: string
  _type: 'project'
  _updatedAt: string
  status: 'draft' | 'published'
  title: string
  slug: string
  category: string
  area: string | null
  year: string | null
  location: string | null
  story: Array<{
    en: string
    es: string
  }> | null
  portfolio_image: string
  other_projects_image: string
  project_page_image: string
  gallery_media: Array<{
    src: string
    alt: string
    gif: string | null
    mp4: string | null
    position: number
  }>
  information_media: Array<{
    src: string
    alt: string
    gif: string | null
    mp4: string | null
    position: number
  }> | null
  gridColumns: '1' | '2' | '3'
  grid_variant: number
  model3d_url: string | null
  date: string
}>

// Source: sanity/lib/queries.ts
// Variable: moreProjectsQuery
// Query: * [_type == "project" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc)[0...$limit] {      _id,  _type,  _updatedAt,  "status": select(_id in path("drafts.**") => "draft", "published"),  "title": select($locale == "es" => title.es, title.en),  "slug": slug.current,  "category": select($locale == "es" => category.es, category.en),  "area": area,  "year": year,  "location": select($locale == "es" => location.es, location.en),  "story": story[]{    "en": en,    "es": es  },  "portfolio_image": portfolio_image,  "other_projects_image": other_projects_image,  "project_page_image": project_page_image,  gallery_media[]{    src,    alt,    gif,    mp4,    position  },  information_media[]{    src,    alt,    gif,    mp4,    position  },  gridColumns,  grid_variant,  model3d_url,  "date": coalesce(date, _updatedAt)}
export type MoreProjectsQueryResult = Array<{
  _id: string
  _type: 'project'
  _updatedAt: string
  status: 'draft' | 'published'
  title: string
  slug: string
  category: string
  area: string | null
  year: string | null
  location: string | null
  story: Array<{
    en: string
    es: string
  }> | null
  portfolio_image: string
  other_projects_image: string
  project_page_image: string
  gallery_media: Array<{
    src: string
    alt: string
    gif: string | null
    mp4: string | null
    position: number
  }>
  information_media: Array<{
    src: string
    alt: string
    gif: string | null
    mp4: string | null
    position: number
  }> | null
  gridColumns: '1' | '2' | '3'
  grid_variant: number
  model3d_url: string | null
  date: string
}>

// Source: sanity/lib/queries.ts
// Variable: projectQuery
// Query: * [_type == "project" && slug.current == $slug][0] {      _id,  _type,  _updatedAt,  "status": select(_id in path("drafts.**") => "draft", "published"),  "title": select($locale == "es" => title.es, title.en),  "slug": slug.current,  "category": select($locale == "es" => category.es, category.en),  "area": area,  "year": year,  "location": select($locale == "es" => location.es, location.en),  "story": story[]{    "en": en,    "es": es  },  "portfolio_image": portfolio_image,  "other_projects_image": other_projects_image,  "project_page_image": project_page_image,  gallery_media[]{    src,    alt,    gif,    mp4,    position  },  information_media[]{    src,    alt,    gif,    mp4,    position  },  gridColumns,  grid_variant,  model3d_url,  "date": coalesce(date, _updatedAt)}
export type ProjectQueryResult = {
  _id: string
  _type: 'project'
  _updatedAt: string
  status: 'draft' | 'published'
  title: string
  slug: string
  category: string
  area: string | null
  year: string | null
  location: string | null
  story: Array<{
    en: string
    es: string
  }> | null
  portfolio_image: string
  other_projects_image: string
  project_page_image: string
  gallery_media: Array<{
    src: string
    alt: string
    gif: string | null
    mp4: string | null
    position: number
  }>
  information_media: Array<{
    src: string
    alt: string
    gif: string | null
    mp4: string | null
    position: number
  }> | null
  gridColumns: '1' | '2' | '3'
  grid_variant: number
  model3d_url: string | null
  date: string
} | null

// Source: sanity/lib/queries.ts
// Variable: siteVisitsQuery
// Query: *[_type == "constructionGallery"][0].visits[$start...$end]{    "id": _key,    photoUrl,    gridSpan,    "projectTitle": select($locale == "es" => project->title.es, project->title.en),    "projectSlug": project->slug.current,    "caption": select($locale == "es" => caption.es, caption.en)  }
export type SiteVisitsQueryResult = Array<{
  id: string
  photoUrl: string | null
  gridSpan: '1' | '2' | 'large' | null
  projectTitle: string | null
  projectSlug: string | null
  caption: string | null
}> | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "settings"][0]': SettingsQueryResult
    '*[_type == "colaborator"] | order(order asc) {\n  _id,\n  name,\n  "role": select($locale == "es" => role.es, role.en),\n  "description": select($locale == "es" => description.es, description.en),\n  "quote": select($locale == "es" => quote.es, quote.en),\n  photoUrl\n}': AllCollaboratorsQueryResult
    '{\n    "project": *[_type == "project" && slug.current == $slug][0] {\n      "title": select($locale == "es" => title.es, title.en),\n      "story": story[]{\n        "en": en,\n        "es": es\n      },\n      "ogImage": ogImage,\n      "portfolio_image": portfolio_image\n    },\n    "settings": *[_type == "settings"][0] {\n      "siteTitle": select($locale == "es" => title.es, title.en),\n      ogImage\n    }\n  }': MetadataProjectQueryResult
    '{\n    "page": *[_type == "page" && slug.current == $slug][0] {\n      "title": select($locale == "es" => title.es, title.en),\n      "description": select($locale == "es" => description.es, description.en),\n      "ogImage": ogImage\n    },\n    "settings": *[_type == "settings"][0] {\n      "siteTitle": select($locale == "es" => title.es, title.en),\n      ogImage\n    }\n  }': MetadataPageQueryResult
    '\n  *[_type == \'page\' && slug.current == $slug][0]{\n    _id,\n    _type,\n    name,\n    slug,\n    heading,\n    subheading,\n    "pageBuilder": pageBuilder[]{\n      ...,\n      _type == "callToAction" => {\n        ...,\n        button {\n          ...,\n          \n  link {\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n      }\n\n        }\n      },\n      _type == "infoSection" => {\n        content[]{\n          ...,\n          markDefs[]{\n            ...,\n            \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n          }\n        }\n      },\n    },\n  }\n': GetPageQueryResult
    '\n  *[_type == "page" || _type == "project" && defined(slug.current)] | order(_type asc) {\n    "slug": slug.current,\n    _type,\n    _updatedAt,\n  }\n': SitemapDataResult
    '\n  *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  "author": author->{firstName, lastName, picture},\n\n  }\n': AllPostsQueryResult
    '\n  *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  "author": author->{firstName, lastName, picture},\n\n  }\n': MorePostsQueryResult
    '\n  *[_type == "post" && slug.current == $slug] [0] {\n    content[]{\n    ...,\n    markDefs[]{\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n    }\n  },\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  "author": author->{firstName, lastName, picture},\n\n  }\n': PostQueryResult
    '\n  *[_type == "post" && defined(slug.current)]\n  {"slug": slug.current}\n': PostPagesSlugsResult
    '\n  *[_type == "page" && defined(slug.current)]\n  {"slug": slug.current}\n': PagesSlugsResult
    '\n    *[_type == "customer"] {\n    \n company,\n contact,\n logo\n\n    }\n  ': AllCustomersResult
    '\n  * [_type == "project" && defined(slug.current)] | order(order asc) {\n    \n  _id,\n  _type,\n  _updatedAt,\n  "status": select(_id in path("drafts.**") => "draft", "published"),\n  "title": select($locale == "es" => title.es, title.en),\n  "slug": slug.current,\n  "category": select($locale == "es" => category.es, category.en),\n  "area": area,\n  "year": year,\n  "location": select($locale == "es" => location.es, location.en),\n  "story": story[]{\n    "en": en,\n    "es": es\n  },\n  "portfolio_image": portfolio_image,\n  "other_projects_image": other_projects_image,\n  "project_page_image": project_page_image,\n  gallery_media[]{\n    src,\n    alt,\n    gif,\n    mp4,\n    position\n  },\n  information_media[]{\n    src,\n    alt,\n    gif,\n    mp4,\n    position\n  },\n  gridColumns,\n  grid_variant,\n  model3d_url,\n  "date": coalesce(date, _updatedAt)\n\n}\n': AllProjectsQueryResult
    '\n  * [_type == "project" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc)[0...$limit] {\n    \n  _id,\n  _type,\n  _updatedAt,\n  "status": select(_id in path("drafts.**") => "draft", "published"),\n  "title": select($locale == "es" => title.es, title.en),\n  "slug": slug.current,\n  "category": select($locale == "es" => category.es, category.en),\n  "area": area,\n  "year": year,\n  "location": select($locale == "es" => location.es, location.en),\n  "story": story[]{\n    "en": en,\n    "es": es\n  },\n  "portfolio_image": portfolio_image,\n  "other_projects_image": other_projects_image,\n  "project_page_image": project_page_image,\n  gallery_media[]{\n    src,\n    alt,\n    gif,\n    mp4,\n    position\n  },\n  information_media[]{\n    src,\n    alt,\n    gif,\n    mp4,\n    position\n  },\n  gridColumns,\n  grid_variant,\n  model3d_url,\n  "date": coalesce(date, _updatedAt)\n\n}\n': MoreProjectsQueryResult
    '\n  * [_type == "project" && slug.current == $slug][0] {\n    \n  _id,\n  _type,\n  _updatedAt,\n  "status": select(_id in path("drafts.**") => "draft", "published"),\n  "title": select($locale == "es" => title.es, title.en),\n  "slug": slug.current,\n  "category": select($locale == "es" => category.es, category.en),\n  "area": area,\n  "year": year,\n  "location": select($locale == "es" => location.es, location.en),\n  "story": story[]{\n    "en": en,\n    "es": es\n  },\n  "portfolio_image": portfolio_image,\n  "other_projects_image": other_projects_image,\n  "project_page_image": project_page_image,\n  gallery_media[]{\n    src,\n    alt,\n    gif,\n    mp4,\n    position\n  },\n  information_media[]{\n    src,\n    alt,\n    gif,\n    mp4,\n    position\n  },\n  gridColumns,\n  grid_variant,\n  model3d_url,\n  "date": coalesce(date, _updatedAt)\n\n}\n': ProjectQueryResult
    '\n  *[_type == "constructionGallery"][0].visits[$start...$end]{\n    "id": _key,\n    photoUrl,\n    gridSpan,\n    "projectTitle": select($locale == "es" => project->title.es, project->title.en),\n    "projectSlug": project->slug.current,\n    "caption": select($locale == "es" => caption.es, caption.en)\n  }\n': SiteVisitsQueryResult
  }
}
